project:
  type: website

website:
  title: "HALFpipe"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: About
      - file: quality-control.qmd
        text: Quality Control
      - file: analysis.ipynb
        text: Analysis
      - file: manual_old_ui.qmd
        text: Manual Old UI

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
